export const ATTRACTION_NAMES = [
  'Universal Studios - Fixed Date',
  'Add on : Universal Studios - Express pass from',
  'Combo : Cable Car + Madame Tussauds + Wings of Time',
  'Singapore Ocenarium ( Peak - Fixed Date )',
  'SkyLine Luge - Peak ( 3 rides )-Fixed Date/Time',
  'Adventure Cove Park - Fixed Date',
  '4D Adventure land (4-in-1 combo)',
  'Madame Tussauds (MT) with Digiphoto + Snacks',
  'Mega Zip, Climb & Jump',
  'Harry Potter : Visions of Magic - Peak',
  'Cable Car (CC) - round trip',
  'MegaZip',
  'Altitude ( iFly )',
  'Wings of Time ( WOT ) - Fixed date / Time',
  'Fun Pass tokens',
  'Sky Helix',
  'Flyer',
  'Duck Tour / Dukw Tour - Fixed Date / Time',
  'Floral Fantasy - Disney Garden of Wonder',
  'Gardens (Cloud F - Jurassic Park + Flower Dome)',
  'River Cruise ( from Clark Quay Jetty )',
  'Big Bus Hop On Hop Off (Day Tour) - city tour',
  'MBS Sky Park ( Peak - Fixed date /Time )',
  'ArtScienceMusuem-Future World -Fixed date/Time',
  'Rainforest Wild Asia - Fixed Date / Time',
  'Zoo with Tram - Fixed Date',
  'Night Safari w Tram - Fixed Date / Time',
  'River Wonders- Fixed Date',
  'Bird Paradise - Fixed Date',
  '6 parks destination pass ( In 1 day )',
  'Museum Of Icecreams - Fixed Date / Time',
  'SkyLine Luge - OFF Peak ( 3 rides )-Fixed Date/Time',
  'Canopy Park',
  'Canopy Bridge ( Includes Canopy Park )',
  'Hedge Maze ( Includes Canopy Park )',
  'Mirror Maze ( Includes Canopy Park )',
  'Walking Net (Includes Canopy Park )',
  'Bouncing Net (Includes Canopy Park )',
  'Experience Studio',
  'Science Centre',
  'Omni Theatre',
  'Science Centre + omni Theatre',
  'Science Centre + KidsStop',
  'KidsStop',
  'Snow City - 1 hr Play + Dyed Ice Play ground',
  'Snow City - 2 hr Play + Dyed Ice Play ground',
  'Snow City - 1 hr+ Bumper Car',
  'SuperTree Observatory - Fixed Date',
  'Dolphin Observer + Oceanarium - Fixed Date / Time',
  'Dolphin Exploration + Oceanarium - Fixed Date / Time',
  'Dolphin Immersion + Oceanarium - Fixed Date / Time',
  'Dolphin Connection + Oeanarium - Fixed Date / Time'
]
