import { defineType, defineField } from 'sanity'

export const b2bServiceMediaSchema = defineType({
  name: 'b2bServiceMedia',
  title: 'Services Catalog Items (Hotels, Restaurants, Guides, Tours)',
  type: 'document',
  fields: [
    defineField({
      name: 'category',
      title: 'Service Category',
      type: 'string',
      options: {
        list: [
          { title: '🎡 Attraction Showcase', value: 'attraction' },
          { title: '🏨 Partner Hotel & Resort', value: 'hotel' },
          { title: '🍽️ Restaurant / Dining', value: 'restaurant' },
          { title: '🚩 Licensed Tour Guide', value: 'guide' },
          { title: '🚍 Tour (2N/3N/4N & City Tours)', value: 'tour' },
          { title: '📦 B2B Package Circuit', value: 'package' },
        ],
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'isDisplayed',
      title: 'Display in Services Catalog',
      type: 'boolean',
      initialValue: true,
      description: 'Toggle ON (green) to display this item/hotel/attraction in the catalog, or toggle OFF to temporarily hide it.',
    }),
    defineField({
      name: 'title',
      title: 'Item Title / Name',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'URL Slug (Direct Page Link)',
      type: 'slug',
      options: {
        source: 'title',
        maxLength: 96,
      },
      description: 'Generates direct individual URL link, e.g. /services-catalog/attractions/universal-studios-singapore or /services-catalog/hotels/hotel-chancellor-orchard',
    }),
    defineField({
      name: 'subtitle',
      title: 'Subtitle / Tagline',
      type: 'string',
    }),
    defineField({
      name: 'destination',
      title: 'Destination',
      type: 'string',
      options: {
        list: [
          { title: 'Singapore', value: 'Singapore' },
          { title: 'Malaysia', value: 'Malaysia' },
          { title: 'Cross Border (SG + MY)', value: 'Cross Border' },
        ],
      },
      initialValue: 'Singapore',
    }),
    defineField({
      name: 'description',
      title: 'Detailed Description / Overview',
      type: 'text',
      rows: 4,
    }),
    defineField({
      name: 'mustDoThings',
      title: 'Must-Do Things & Key Experiences (Bullet Points)',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'List signature rides, shows, exhibits, or room experiences (e.g. "Battlestar Galactica Coaster", "Creatures of the Night Show", "Rooftop Pool").',
    }),
    defineField({
      name: 'timings',
      title: 'Operating Hours / Timings & Best Time to Visit',
      type: 'string',
      description: 'e.g. "10:00 AM – 7:00 PM (Daily); Best time: Weekday mornings to avoid peak crowds"',
    }),
    defineField({
      name: 'tipsAndTricks',
      title: 'Tips & Trips / Pro-Tips & Practical Advice',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Add insider tips, ticket hacks, queue strategies, what to wear, transit routes, etc.',
    }),
    defineField({
      name: 'appDetails',
      title: 'Official Mobile App Details (Visitor Apps)',
      type: 'object',
      fields: [
        { name: 'appName', title: 'App Name', type: 'string', description: 'e.g. Universal Studios Singapore Official App' },
        { name: 'appDescription', title: 'Short App Description', type: 'string', description: 'e.g. Live ride wait times, interactive GPS map & mobile ordering' },
        { name: 'appStoreUrl', title: 'Apple App Store URL (iOS)', type: 'url' },
        { name: 'playStoreUrl', title: 'Google Play Store URL (Android)', type: 'url' },
        { name: 'appFeatures', title: 'Key App Features', type: 'array', of: [{ type: 'string' }] },
      ],
      description: 'Mobile visitor app download details and features.',
    }),
    defineField({
      name: 'coverImage',
      title: 'Cover Image Upload (Direct Computer Upload)',
      type: 'image',
      options: { hotspot: true },
      description: 'Upload cover photo directly from your computer or phone.',
    }),
    defineField({
      name: 'coverImageUrl',
      title: 'Cover Image URL (Alternative Text Link)',
      type: 'string',
      description: 'Or paste an image URL e.g. https://images.unsplash.com/...',
    }),
    defineField({
      name: 'videoFile',
      title: 'Video Showcase Upload (Direct MP4/WebM Video Upload)',
      type: 'file',
      options: { accept: 'video/*' },
      description: 'Upload video file directly from your computer.',
    }),
    defineField({
      name: 'videoUrl',
      title: 'Video Showcase URL (YouTube, Vimeo, MP4 link)',
      type: 'string',
      description: 'Or paste a YouTube/Vimeo/MP4 link.',
    }),
    defineField({
      name: 'galleryImages',
      title: 'Photo Gallery Uploads (Direct Multiple Photo Upload)',
      type: 'array',
      of: [{ type: 'image', options: { hotspot: true } }],
      description: 'Upload multiple photos of rides, exhibits, interiors, food, or tour highlights.',
    }),
    defineField({
      name: 'galleryImageUrls',
      title: 'Photo Gallery URLs (Alternative Text Links)',
      type: 'array',
      of: [{ type: 'string' }],
    }),
    defineField({
      name: 'features',
      title: 'Key Features / Tags (comma-separated)',
      type: 'array',
      of: [{ type: 'string' }],
    }),
    defineField({
      name: 'duration',
      title: 'Duration (For Attractions & Tours e.g. 6–8 Hours, Full Day, 2N/3D)',
      type: 'string',
    }),
    defineField({
      name: 'spokenLanguages',
      title: 'Spoken Languages (For Guides)',
      type: 'array',
      of: [{ type: 'string' }],
    }),
    defineField({
      name: 'cuisineType',
      title: 'Cuisine Type (For Restaurants e.g. Halal, Seafood, Indian)',
      type: 'string',
    }),
    defineField({
      name: 'starRating',
      title: 'Star Rating (For Hotels e.g. 4-Star, 5-Star, Luxury Resort)',
      type: 'string',
      options: {
        list: ['3-Star', '3.5-Star', '4-Star', '5-Star', 'Luxury Resort', 'Boutique Hotel'],
      },
    }),
    defineField({
      name: 'hotelAddress',
      title: 'Address & Nearest MRT Station',
      type: 'string',
      description: 'e.g. 28 Cavenagh Road (Near Somerset MRT), Singapore 229635',
    }),
    defineField({
      name: 'roomCategories',
      title: 'Room Categories & Amenities (For Hotels)',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'e.g. Deluxe Room, Superior City View, Family Suite with Balcony',
    }),
    defineField({
      name: 'shorts',
      title: 'Curated YouTube Shorts (Vertical Reels)',
      type: 'array',
      of: [
        {
          type: 'object',
          fields: [
            { name: 'title', title: 'Short Title', type: 'string' },
            { name: 'creator', title: 'Creator / Channel Name', type: 'string' },
            { name: 'views', title: 'Views Text (e.g. 500K views)', type: 'string' },
            { name: 'thumbnailUrl', title: 'Thumbnail Image URL', type: 'string' },
            { name: 'youtubeVideoId', title: 'YouTube Video ID / Short ID', type: 'string' },
          ],
        },
      ],
      description: 'Add vertical 9:16 YouTube Shorts for ride walkthroughs, animal encounters, and room tours.',
    }),
  ],
})
