export const siteSettingsSchema = {
  name: 'siteSettings',
  title: 'Site Settings & Content',
  type: 'document',
  groups: [
    { name: 'b2bToggles', title: '🛠️ B2B Builder & Portal Toggles', default: true },
    { name: 'navigationToggles', title: '🙈 Main Site Page Hide Toggles' },
    { name: 'paymentSettings', title: '💳 Payment & UPI Gateway Controls' },
    { name: 'exchangeRate', title: '🔀 SGD to INR Exchange Rate' },
    { name: 'heroContent', title: '🌐 Homepage & Brand Content' },
  ],
  fields: [

    /* ══════ 1. B2B BUILDER & PORTAL TOGGLES ══════ */
    {
      name: 'hideReadyTemplatesSubpage',
      title: '🙈 Hide "Ready-Made Packages" Subpage',
      type: 'boolean',
      description: 'Toggle ON to completely hide the Ready-Made Packages tab on the B2B Custom Package portal.',
      initialValue: false,
      group: 'b2bToggles',
    },
    {
      name: 'hideCustomPackageClientPreview',
      title: '🙈 Hide "Client-Ready Preview" Tab',
      type: 'boolean',
      description: 'Toggle ON to hide the Client-Ready Preview tab on the B2B Custom Package portal.',
      initialValue: false,
      group: 'b2bToggles',
    },
    {
      name: 'hidePreviewPackageOverlay',
      title: '🙈 Hide "Preview Package" Floating Button',
      type: 'boolean',
      description: 'Toggle ON to hide the green "Preview Package" button from the B2B toolbar.',
      initialValue: false,
      group: 'b2bToggles',
    },
    {
      name: 'hideIciciCustomPackage',
      title: '🙈 Hide "UPI - Pay" Button on B2B Portal',
      type: 'boolean',
      description: 'Toggle ON to hide the UPI ICICI Payment button from the B2B portal.',
      initialValue: false,
      group: 'b2bToggles',
    },
    {
      name: 'hideCashfreeCustomPackage',
      title: '🙈 Hide "Credit Card - Pay" Button on B2B Portal',
      type: 'boolean',
      description: 'Toggle ON to hide the Credit Card payment button from the B2B portal.',
      initialValue: false,
      group: 'b2bToggles',
    },
    {
      name: 'customPackageSheetUrl',
      title: '📊 Custom Package Master Pricing Google Sheet CSV URL',
      type: 'url',
      description: 'Published Google Sheet CSV link for Custom Package Hotels, Transfers, Guides, and Meals master rates.',
      group: 'b2bToggles',
    },


    /* ══════ 2. NAVIGATION & MAIN SITE HIDE TOGGLES ══════ */
    {
      name: 'hideInstantQuote',
      title: '🙈 Hide "Instant Quote" Page',
      type: 'boolean',
      description: 'Toggle ON to hide the Instant Quote page and link across the site.',
      initialValue: true,
      group: 'navigationToggles',
    },
    {
      name: 'hideCustomPackage',
      title: '🙈 Hide "Custom Package" Page',
      type: 'boolean',
      description: 'Toggle ON to hide the Custom Package Estimator link across the site.',
      initialValue: false,
      group: 'navigationToggles',
    },
    {
      name: 'hideSingaporeAttractions',
      title: '🙈 Hide "Singapore Attractions" Page',
      type: 'boolean',
      description: 'Toggle ON to hide the Singapore Attractions link across the site.',
      initialValue: false,
      group: 'navigationToggles',
    },
    {
      name: 'hidePackages',
      title: '🙈 Hide "Packages" Page',
      type: 'boolean',
      description: 'Toggle ON to hide the Packages link across the site.',
      initialValue: false,
      group: 'navigationToggles',
    },
    {
      name: 'hideBrochure',
      title: '🙈 Hide "Brochure" Page',
      type: 'boolean',
      description: 'Toggle ON to hide the Brochure link across the site.',
      initialValue: false,
      group: 'navigationToggles',
    },
    {
      name: 'hideReviews',
      title: '🙈 Hide "Reviews" Page',
      type: 'boolean',
      description: 'Toggle ON to hide the Reviews link across the site.',
      initialValue: false,
      group: 'navigationToggles',
    },
    {
      name: 'hideBlog',
      title: '🙈 Hide "Blog" Page',
      type: 'boolean',
      description: 'Toggle ON to hide the Blog link across the site.',
      initialValue: false,
      group: 'navigationToggles',
    },
    {
      name: 'hideContact',
      title: '🙈 Hide "Contact" Page',
      type: 'boolean',
      description: 'Toggle ON to hide the Contact link across the site.',
      initialValue: false,
      group: 'navigationToggles',
    },
    {
      name: 'hideChatbot',
      title: '🙈 Hide AI Chatbot Assistant',
      type: 'boolean',
      description: 'Toggle ON to hide the FlyBot AI Assistant across the entire website.',
      initialValue: false,
      group: 'navigationToggles',
    },
    {
      name: 'hideFaq',
      title: '🙈 Hide "FAQ" Page',
      type: 'boolean',
      description: 'Toggle ON to hide the FAQ link in the global footer.',
      initialValue: false,
      group: 'navigationToggles',
    },
    {
      name: 'hideAiPlanner',
      title: '🙈 Hide "AI Journey Planner"',
      type: 'boolean',
      description: 'Toggle ON to hide the AI Journey Planner button on the homepage.',
      initialValue: false,
      group: 'navigationToggles',
    },


    /* ══════ 3. PAYMENT & UPI GATEWAY SETTINGS ══════ */
    {
      name: 'iciciUpiId',
      title: 'ICICI Bank: UPI ID (VPA)',
      type: 'string',
      description: 'Your ICICI Bank UPI VPA ID (e.g., flyingwonders@icici)',
      initialValue: 'flyingwonders@icici',
      group: 'paymentSettings',
    },
    {
      name: 'iciciAccountName',
      title: 'ICICI Bank: Account Name',
      type: 'string',
      initialValue: 'Flying Wonders Pvt Ltd',
      group: 'paymentSettings',
    },
    {
      name: 'iciciBankDetails',
      title: 'ICICI Bank: Full Account & IFSC Details',
      type: 'text',
      description: 'Bank Account Number, IFSC Code, Branch details shown on payment screen.',
      initialValue: 'Account No: 0000 1234 5678 | IFSC: ICIC0000001 | Branch: Bangalore Main Branch',
      group: 'paymentSettings',
    },
    {
      name: 'iciciQrImage',
      title: 'ICICI Bank: UPI QR Code Image',
      type: 'image',
      description: 'Upload your high-res ICICI Bank UPI QR code image here.',
      options: { hotspot: true },
      group: 'paymentSettings',
    },
    {
      name: 'hideIciciInstantQuote',
      title: '🙈 Hide ICICI UPI Payment on "Instant Quote" Page',
      type: 'boolean',
      initialValue: false,
      group: 'paymentSettings',
    },
    {
      name: 'hideIciciAttractions',
      title: '🙈 Hide ICICI UPI Payment on "Singapore Attractions" Page',
      type: 'boolean',
      initialValue: false,
      group: 'paymentSettings',
    },
    {
      name: 'hideIciciPackages',
      title: '🙈 Hide ICICI UPI Payment on "Packages" Page',
      type: 'boolean',
      initialValue: false,
      group: 'paymentSettings',
    },
    {
      name: 'hideIciciPayDirect',
      title: '🙈 Hide ICICI UPI Payment on "Pay Direct" Page',
      type: 'boolean',
      initialValue: false,
      group: 'paymentSettings',
    },


    /* ══════ 4. SGD TO INR EXCHANGE RATE ══════ */
    {
      name: 'exchangeMarkupType',
      title: 'INR Conversion: Markup Type',
      type: 'string',
      options: {
        list: [
          { title: 'Absolute (INR Amount per SGD, e.g., + ₹3.50)', value: 'absolute' },
          { title: 'Percentage (%, e.g., + 2.5%)', value: 'percentage' },
        ]
      },
      initialValue: 'absolute',
      group: 'exchangeRate',
    },
    {
      name: 'exchangeMarkupValue',
      title: 'INR Conversion: Markup Value',
      type: 'number',
      description: 'Type the absolute INR value (e.g. 3.5 for +₹3.50/SGD) or percentage value.',
      initialValue: 3.5,
      group: 'exchangeRate',
    },
    {
      name: 'manualRateOverride',
      title: 'INR Conversion: Manual Fixed Rate Override',
      type: 'number',
      description: 'Optional. Type a fixed SGD to INR rate (e.g. 66.50) to ignore live market APIs.',
      group: 'exchangeRate',
    },


    /* ══════ 5. HOMEPAGE & BRAND CONTENT ══════ */
    {
      name: 'heroTitle',
      title: 'Hero Title',
      type: 'string',
      initialValue: 'Where the Future Lives. Experience Singapore.',
      group: 'heroContent',
    },
    {
      name: 'heroSubtitle',
      title: 'Hero Subtitle',
      type: 'text',
      initialValue: 'Discover a global hub of innovation, Michelin-starred heritage, and luxury living wrapped inside a city of tomorrow.',
      group: 'heroContent',
    },
    {
      name: 'aboutVisionStatement',
      title: 'About Us: Vision Statement',
      type: 'text',
      initialValue: 'Flying Wonders is Singapore’s premier B2B Destination Management Company, architecting Group tours , high-end MICE execution and hyper-curated leisure experiences for global travel partners ',
      group: 'heroContent',
    },
    {
      name: 'aboutStoryTitle',
      title: 'About Us: Story Title',
      type: 'string',
      initialValue: 'Our Story & Strategy',
      group: 'heroContent',
    },
    {
      name: 'aboutStoryParagraph1',
      title: 'About Us: Story Paragraph 1',
      type: 'text',
      initialValue: 'Flying Wonders Private Limited is a specialist Destination Management Company (DMC) based in India & Singapore. We design and deliver premium travel experiences across Singapore, South-East Asia and beyond — for leisure groups, corporate travellers and trade partners who demand more than a standard package.',
      group: 'heroContent',
    },
    {
      name: 'aboutStoryParagraph2',
      title: 'About Us: Story Paragraph 2',
      type: 'text',
      initialValue: 'With direct hotel partnerships, exclusive ground assets and a passionate team of travel architects, we turn every itinerary into a story worth telling. From iconic Singapore sights to hidden regional gems, Flying Wonders brings the destination to life.',
      group: 'heroContent',
    },
    {
      name: 'aboutStrategicAdvantage',
      title: 'About Us: Strategic Advantage Narrative',
      type: 'text',
      initialValue: 'We operate and maintain office structures in Both India and Singapore , clients benefits from professional service and local expertise.',
      group: 'heroContent',
    },
    {
      name: 'aboutTrustAndComplianceDesk',
      title: 'About Us: Localized Crisis Desk Callout',
      type: 'string',
      initialValue: '24/7 localized rapid-response crisis desk',
      group: 'heroContent',
    },
    {
      name: 'attractionsBannerText',
      title: 'Attractions Page: Rolling Banner Text',
      type: 'string',
      initialValue: 'Complimentary tickets :  Wings of time for 8:30 PM show - Click Here',
      group: 'heroContent',
    },
    {
      name: 'attractionsBannerActive',
      title: 'Attractions Page: Show Rolling Banner',
      type: 'boolean',
      initialValue: true,
      group: 'heroContent',
    },
    {
      name: 'attractionsBannerWhatsappMessage',
      title: 'Attractions Page: WhatsApp prefilled message',
      type: 'text',
      initialValue: 'Hi Flying Wonders, I would like to request the complimentary tickets for the Wings of Time 8:30 PM show.',
      group: 'heroContent',
    },
    {
      name: 'attractionsSheetUrl',
      title: '📊 Attractions Pricing Google Sheet CSV URL',
      type: 'url',
      description: 'Published Google Sheet CSV link for Singapore Attraction ticket prices.',
      initialValue: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQlNHAbUt7ldY7my-EXF1VZq4s2eQ7y3YzZm8z6vFLfUH4KYKHw3G03FK60DlgQ_fGUN1Hz1qIBFqUT/pub?output=csv',
      group: 'heroContent',
    },
    {
      name: 'notificationEmails',
      title: 'Notification Recipient Emails',
      type: 'string',
      description: 'Comma-separated list of emails to receive booking, inquiry, and agent notifications.',
      initialValue: 'info.flyingwonders@gmail.com',
      group: 'heroContent',
    },
  ],
}
