export const siteSettingsSchema = {
  name: 'siteSettings',
  title: 'Site Settings & Content',
  type: 'document',
  fields: [
    {
      name: 'heroTitle',
      title: 'Hero Title',
      type: 'string',
      initialValue: 'Where the Future Lives. Experience Singapore.',
    },
    {
      name: 'heroSubtitle',
      title: 'Hero Subtitle',
      type: 'text',
      initialValue: 'Discover a global hub of innovation, Michelin-starred heritage, and luxury living wrapped inside a city of tomorrow.',
    },

    {
      name: 'aboutVisionStatement',
      title: 'About Us: Vision Statement',
      type: 'text',
      initialValue: 'Flying Wonders is Singapore’s premier B2B Destination Management Company, architecting Group tours , high-end MICE execution and hyper-curated leisure experiences for global travel partners ',
    },
    {
      name: 'aboutStrategicAdvantage',
      title: 'About Us: Strategic Advantage Narrative',
      type: 'text',
      initialValue: 'We operate and maintain office structures in Both India and Singapore , clients benefits from professional service and local expertise.',
    },
    {
      name: 'aboutTrustAndComplianceDesk',
      title: 'About Us: Localized Crisis Desk Callout',
      type: 'string',
      initialValue: '24/7 localized rapid-response crisis desk',
    },
    {
      name: 'attractionsBannerText',
      title: 'Attractions Page: Rolling Banner Text',
      type: 'string',
      initialValue: 'Complimentary tickets :  Wings of time for 8:30 PM show - Click Here',
    },
    {
      name: 'attractionsBannerActive',
      title: 'Attractions Page: Show Rolling Banner',
      type: 'boolean',
      initialValue: true,
    },
    {
      name: 'attractionsBannerWhatsappMessage',
      title: 'Attractions Page: WhatsApp prefilled message',
      type: 'text',
      initialValue: 'Hi Flying Wonders, I would like to request the complimentary tickets for the Wings of Time 8:30 PM show.',
    },

    {
      name: 'itinerarySectionTitle',
      title: 'Itinerary Section Title',
      type: 'string',
      initialValue: 'The Itinerary for Wonders',
    },
    {
      name: 'card1Tagline',
      title: 'Card 1 Tagline',
      type: 'string',
      initialValue: 'SENSORY JOURNEYS',
    },
    {
      name: 'card1Header',
      title: 'Card 1 Header',
      type: 'string',
      initialValue: 'Taste the World in a Single Square Mile',
    },
    {
      name: 'card1Story',
      title: 'Card 1 Story (Sub-text)',
      type: 'text',
      initialValue: 'A collision of cross-cultural heritage and culinary artistry. Lose yourself in the generational smoke of legendary hawker street stalls, or ascend to the stars for avant-garde dining suspended high above the glittering skyline.',
    },
    {
      name: 'card1Image',
      title: 'Card 1 Image URL',
      type: 'string',
      initialValue: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
    },
    {
      name: 'card2Tagline',
      title: 'Card 2 Tagline',
      type: 'string',
      initialValue: 'REGENERATIVE EXPLORATION',
    },
    {
      name: 'card2Header',
      title: 'Card 2 Header',
      type: 'string',
      initialValue: "The World's Finest City in Nature",
    },
    {
      name: 'card2Story',
      title: 'Card 2 Story (Sub-text)',
      type: 'text',
      initialValue: 'Step into a living blueprint for tomorrow’s travel. Wander through an eco-futuristic wonderland where high-density vertical gardens breathe alongside bioluminescent glass domes, redefining the boundary between urban luxury and the wild.',
    },
    {
      name: 'card2Image',
      title: 'Card 2 Image URL',
      type: 'string',
      initialValue: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
    },
    {
      name: 'card3Tagline',
      title: 'Card 3 Tagline',
      type: 'string',
      initialValue: 'THE BLEISURE ESCAPE',
    },
    {
      name: 'card3Header',
      title: 'Card 3 Header',
      type: 'string',
      initialValue: 'Where Global Ambition Meets Uncharted Play',
    },
    {
      name: 'card3Story',
      title: 'Card 3 Story (Sub-text)',
      type: 'text',
      initialValue: 'The ultimate playground for the modern global traveler. Effortlessly transition from high-stakes networking summits in architectural marvels to pulse-pounding nightlife, world-class Grand Prix weekends, and sun-soaked offshore island retreats.',
    },
    {
      name: 'card3Image',
      title: 'Card 3 Image URL',
      type: 'string',
      initialValue: 'https://images.unsplash.com/photo-1596464716127-f2a82984de30?auto=format&fit=crop&w=800&q=80',
    },
    {
      name: 'notificationEmails',
      title: 'Notification Recipient Emails',
      type: 'string',
      description: 'Comma-separated list of emails to receive booking, inquiry, and agent notifications.',
      initialValue: 'info.flyingwonders@gmail.com',
    },
    {
      name: 'hideInstantQuote',
      title: '🙈 Hide "Instant Quote" Page',
      type: 'boolean',
      description: 'Toggle ON to hide the Instant Quote page and link across the site.',
      initialValue: true,
    },
    {
      name: 'hideCustomPackage',
      title: '🙈 Hide "Custom Package" Page',
      type: 'boolean',
      description: 'Toggle ON to hide the Custom Package Estimator link across the site.',
      initialValue: false,
    },
    {
      name: 'hideSingaporeAttractions',
      title: '🙈 Hide "Singapore Attractions" Page',
      type: 'boolean',
      description: 'Toggle ON to hide the Singapore Attractions link across the site.',
      initialValue: false,
    },
    {
      name: 'hidePackages',
      title: '🙈 Hide "Packages" Page',
      type: 'boolean',
      description: 'Toggle ON to hide the Packages link across the site.',
      initialValue: false,
    },
    {
      name: 'hideBrochure',
      title: '🙈 Hide "Brochure" Page',
      type: 'boolean',
      description: 'Toggle ON to hide the Brochure link across the site.',
      initialValue: false,
    },
    {
      name: 'hideReviews',
      title: '🙈 Hide "Reviews" Page',
      type: 'boolean',
      description: 'Toggle ON to hide the Reviews link across the site.',
      initialValue: false,
    },
    {
      name: 'hideBlog',
      title: '🙈 Hide "Blog" Page',
      type: 'boolean',
      description: 'Toggle ON to hide the Blog link across the site.',
      initialValue: false,
    },
    {
      name: 'hideContact',
      title: '🙈 Hide "Contact" Page',
      type: 'boolean',
      description: 'Toggle ON to hide the Contact link across the site.',
      initialValue: false,
    },
    {
      name: 'hideChatbot',
      title: '🙈 Hide AI Chatbot Assistant',
      type: 'boolean',
      description: 'Toggle ON to hide the FlyBot AI Assistant across the entire website.',
      initialValue: false,
    },
    {
      name: 'hideFaq',
      title: '🙈 Hide "FAQ" Page',
      type: 'boolean',
      description: 'Toggle ON to hide the FAQ link in the global footer.',
      initialValue: false,
    },
    {
      name: 'hideAiPlanner',
      title: '🙈 Hide "AI Journey Planner"',
      type: 'boolean',
      description: 'Toggle ON to hide the AI Journey Planner button on the homepage.',
      initialValue: false,
    },

    /* GOOGLE SHEETS DYNAMIC PRICING URLS */
    {
      name: 'attractionsSheetUrl',
      title: '📊 Attractions Pricing Google Sheet CSV URL',
      type: 'url',
      description: 'Published Google Sheet CSV link for Singapore Attraction ticket prices.',
      initialValue: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQlNHAbUt7ldY7my-EXF1VZq4s2eQ7y3YzZm8z6vFLfUH4KYKHw3G03FK60DlgQ_fGUN1Hz1qIBFqUT/pub?output=csv',
    },
    {
      name: 'customPackageSheetUrl',
      title: '📊 Custom Package Master Pricing Google Sheet CSV URL',
      type: 'url',
      description: 'Published Google Sheet CSV link for Custom Package Hotels, Transfers, Guides, and Meals master rates.',
    },

    /* ICICI BANK & UPI CONFIGURATION */
    {
      name: 'iciciUpiId',
      title: 'ICICI Bank: UPI ID (VPA)',
      type: 'string',
      description: 'Your ICICI Bank UPI VPA ID (e.g., flyingwonders@icici)',
      initialValue: 'flyingwonders@icici',
    },
    {
      name: 'iciciAccountName',
      title: 'ICICI Bank: Account Name',
      type: 'string',
      initialValue: 'Flying Wonders Pvt Ltd',
    },
    {
      name: 'iciciBankDetails',
      title: 'ICICI Bank: Full Account & IFSC Details',
      type: 'text',
      description: 'Bank Account Number, IFSC Code, Branch details shown on payment screen.',
      initialValue: 'Account No: 0000 1234 5678 | IFSC: ICIC0000001 | Branch: Bangalore Main Branch',
    },
    {
      name: 'iciciQrImage',
      title: 'ICICI Bank: UPI QR Code Image',
      type: 'image',
      description: 'Upload your high-res ICICI Bank UPI QR code image here.',
      options: { hotspot: true },
    },

    /* EXCHANGE RATE MARKUP CONFIGURATION */
    {
      name: 'exchangeMarkupType',
      title: 'INR Conversion: Markup Type',
      type: 'string',
      options: {
        list: [
          { title: 'Absolute (INR Amount per SGD, e.g., + ₹3.50)', value: 'absolute' },
          { title: 'Percentage (%, e.g., + 2.5%)', value: 'percentage' },
        ]
      },
      initialValue: 'absolute',
    },
    {
      name: 'exchangeMarkupValue',
      title: 'INR Conversion: Markup Value',
      type: 'number',
      description: 'Type the absolute INR value (e.g. 3.5 for +₹3.50/SGD) or percentage value.',
      initialValue: 3.5,
    },
    {
      name: 'manualRateOverride',
      title: 'INR Conversion: Manual Fixed Rate Override',
      type: 'number',
      description: 'Optional. Type a fixed SGD to INR rate (e.g. 66.50) to ignore live market APIs.',
    },

    /* PAGE-LEVEL HIDE TOGGLES FOR ICICI UPI PAYMENT */
    {
      name: 'hideIciciCustomPackage',
      title: '🙈 Hide ICICI UPI Payment on "Custom Package" Page',
      type: 'boolean',
      initialValue: false,
    },
    {
      name: 'hideIciciInstantQuote',
      title: '🙈 Hide ICICI UPI Payment on "Instant Quote" Page',
      type: 'boolean',
      initialValue: false,
    },
    {
      name: 'hideIciciAttractions',
      title: '🙈 Hide ICICI UPI Payment on "Singapore Attractions" Page',
      type: 'boolean',
      initialValue: false,
    },
    {
      name: 'hideIciciPackages',
      title: '🙈 Hide ICICI UPI Payment on "Packages" Page',
      type: 'boolean',
      initialValue: false,
    },
    {
      name: 'hideIciciPayDirect',
      title: '🙈 Hide ICICI UPI Payment on "Pay Direct" Page',
      type: 'boolean',
      initialValue: false,
    },
  ],
}
